### ISSUE TITLE
Having troubles specifying the correct json for PrivateKey

### ISSUE THREAD

**Issue by korompaiistvan** [artem-smotrakov/micropython-rsa-signing#1]
hi, I stumbled upon this repo and I'm hoping to use it to send JWT to Cloud IoT core from an ESP8266. I know I might run into memory issues, and I might switch to the ESP32 myself, but I am not that far yet.

In short my question is, how could I get the json file in the correct format from a pem file created by the following openssl command:
`openssl req -x509 -newkey rsa:2048 -keyout rsa_private.pem -nodes -out rsa_cert.pem -subj "/CN=unused"`

thank you in advance.

**Comment by korompaiistvan** [comment]
prolly noone will look at this issue

**Comment by realvarx** [comment]
Did you find the way to get from certificate to json? @korompaiistvan

**Comment by korompaiistvan** [comment]
Nah I always ran out of ram, so I gave up.

**Comment by realvarx** [comment]
And did you find a way outside of the board (on a PC)? I just want to provide the correct json to the board, I dont mind converting the certificate to that json in another device @korompaiistvan

**Comment by korompaiistvan** [comment]
My original idea was to connect the esp8266 to the internet and upload data
to a cloud provider, over https but that failed due to this limitation.

Instead I set up a local server (raspi) that serves as an MQTT broker so
communication on the local network can be unsafe. Note that I'm not sending
any sensitive data so this is fine.
